dataset: MNIST

training:
  download: true
  epochs: 100
  learning_rate: 0.001
  batch_size: 32
  subepochs: 10

validation:
  interval: 1  # Validate every epoch

network:
  name: DenseNet
  input_shape: [28, 28]
  output_shape: [28, 28]
  channel_list: [784, 1024, 8192, 1024, 784]
  activation: prelu

sde:
  type: SongVarianceExploding
  sigma_1: 80

wandb:
  project: "your_project_name"
  entity: "your_entity_name"
  log_interval: 1  # Log every epoch